ci:
  autofix_commit_msg: |
        [pre-commit.ci] auto fixes from pre-commit.com hooks

        for more information, see https://pre-commit.ci
  autofix_prs: true
  skip:
    - "pytest-check"

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: detect-private-key
    -   id: requirements-txt-fixer
    -   id: no-commit-to-branch
    args: [--branch, master, --pattern, release/.*]
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.7.0  # Use the sha / tag you want to point at
    hooks:
    -   id: autopep8
-   repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
